[package]
name = "SynthVst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
# add some dependencies here
vst = "0.3"
rand = "0.8"